### ISSUE TITLE
Collection AQUARIUS_L2_SSS_V5 failing in l2ss-py and concise

### ISSUE THREAD

**Issue by jamesfwood** [podaac/concise#68]
https://github.com/podaac/concise/actions/runs/5650449377/job/15306806841

**Comment by sliu008** [comment]
https://github.com/podaac/concise/pull/78

**Comment by jamesfwood** [comment]
@davidcolemanjpl Test merging in Hitide OPS and UAT

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (UAT): v4.15.0-RC.8
HiTIDE Profile - v4.9.8-rc.1
L2SS-Py - v2.6.0rc3
CONCISE v0.7.0a19

HiTIDE-UI (OPS): v4.15.0
HiTIDE Profile - v4.9.8
L2SS-Py - v2.5.0
CONCISE v0.6.1


HiTIDE-UI (UAT):  **_Test Failed_** 
HiTIDE **UAT** AQUARIUS_L2_SSS_V5 cloud granule downloads are currently failing (_failure happens when 'Merge Granules' enabled or disabled_) 

l2ss-py:2.6.0rc3 (failed):
"WorkItem [3463175] failed with error: podaac/l2ss-py:2.6.0rc3: Service request failed with an unknown error"

See related failed Harmony (UAT) jobIDs: 
e72dbba6-2ab1-4cee-b3e5-34c159b55045, ee3907f7-9901-4b68-90a6-9d4043ad7979, 4df87ff2-142a-4070-bc4a-c9cbd101673d, or 3e460a18-7414-45c1-87f4-9b80ca7cbe2f





HiTIDE-UI (OPS): 
merge/sub-setting functionality PASS

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test subsetting and merging in Hitide UAT only.  Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (UAT): v4.16.0-RC.6
HiTIDE Profile - v4.9.8-rc.1
L2SS-Py - **v2.6.0rc12**
CONCISE uat (v0.7.0a19)

**Test Complete**
