### ISSUE TITLE
Collection SMAP_RSS_L2_SSS_V4 failed to add to concise

### ISSUE THREAD

**Issue by jamesfwood** [podaac/concise#70]
https://github.com/podaac/concise/actions/runs/5650750786

**Comment by sliu008** [comment]
https://github.com/podaac/concise/pull/78

**Comment by jamesfwood** [comment]
@davidcolemanjpl Test merging in Hitide OPS and UAT

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (UAT): v4.15.0-RC.8
HiTIDE Profile - v4.9.8-rc.1
L2SS-Py - v2.6.0rc3
CONCISE v0.7.0a19

HiTIDE-UI (OPS): v4.15.0
HiTIDE Profile - v4.9.8
L2SS-Py - v2.5.0
CONCISE v0.6.1

**_SMAP_RSS_L2_SSS_V4_** cloud dataset:

HiTIDE-UI (**UAT**): Download FAILED (CONCISE failure):
_"WorkItem [3463198] failed with error: podaac/concise:uat: Service failed due to running out of memory"_
See related Harmony (UAT) jobID: aefa2652-57d9-42f5-8d60-dcb198e93254



HiTIDE-UI (**OPS**): Download FAILED (CONCISE failure): 
_"WorkItem [18194395] failed with error: podaac/concise:0.6.1: Service failed due to running out of memory"_
See related Harmony (OPS) jobID: cd4006e4-4e1c-496f-8ece-335b46286491


(note: subsetting currently functions okay when 'Merge Granules' not enabled)

**Comment by sliu008** [comment]
For concise we have out of memory error, maybe ask harmony how much memory is allocated for concise

@timestampSep 5, 2023 @ 16:37:32.011@version1app_messageService failed with error: podaac/concise:uat: Service failed due to running out of memoryenv_nameharmony-uatenvnameuatid37776504594151397307790529350049198333090264709824708610levelerrorlogGroupharmony-uatlogStreampodaac-concise-uat-0-847c4f6d76-v2zb9.managermessage{"env_name":"harmony-uat","level":"error","app_message":"Service failed with error: podaac/concise:uat: Service failed due to running out of memory","timestamp":"2023-09-05T23:37:32.011Z","workItemId":3466033} messageTypeDATA_MESSAGEowner549360732797subscriptionFiltersCloudwatch log filter to forward harmony uat logs to the metrics team.timestamp2023-09-05T23:37:32.011ZworkItemId3,466,033_idto61Z4oB7bRflpnEWDFD_indexcloudwatch-harmony-uat-2023.09.05_score -

**Comment by davidcolemanjpl** [comment]
HiTIDE UI - 4.16.0-RC.6
HiTIDE Profile - 4.9.8-rc.1
L2SS-Py - l2ss-py:2.6.0rc14
CONSISE - concise:uat - 0.7.0a19

**Test Complete**
